- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: update
    apt: upgrade=yes
    environment: proxy_env
  - name: install jdk repo
    apt_repository: repo='ppa:openjdk-r/ppa'
    environment: proxy_env
  - name: install openjdk
    apt: name=openjdk-8-jdk state=present 
    environment: proxy_env
  - name: apt over https
    apt: name=apt-transport-https
    environment: proxy_env
  - name: atlassian apt key
    apt_key: keyserver=keyserver.ubuntu.com id=B07804338C015B73
  - name: install atlassian repo
    apt_repository: repo='deb https://sdkrepo.atlassian.com/debian/ stable contrib'
    environment: proxy_env
  - name: install atlassian sdk
    apt: name=atlassian-plugin-sdk update_cache=yes
    environment: proxy_env
