- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: add repo for java 8
    apt_repository: repo='ppa:webupd8team/java' state=present
    environment: '{{proxy_env}}'
  - name: set licence selected
    shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
    environment: '{{proxy_env}}'
  - name: set licence seen
    shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections
    environment: '{{proxy_env}}'
  - name: install java 8
    apt: name=oracle-java8-installer state=latest update-cache=yes force=yes
    ignore_errors: True
    environment: '{{proxy_env}}'
  - name: apt over https
    apt: name=apt-transport-https
    environment: '{{proxy_env}}'
  - name: atlassian apt key
    apt_key: keyserver=keyserver.ubuntu.com id=B07804338C015B73
  - name: get atlassian sdk
    shell: curl https://sdkrepo.atlassian.com/debian/pool/contrib/a/atlassian-plugin-sdk/atlassian-plugin-sdk_6.2.11_all.deb -o atlassian-plugin-sdk_6.2.11_all.deb
    environment: '{{proxy_env}}'
    ignore_errors: True
  - name: install atlassian sdk
    shell: dpkg -i atlassian-plugin-sdk_6.2.11_all.deb
    environment: '{{proxy_env}}'
    ignore_errors: True
